version: '{build}'
image: Visual Studio 2019
configuration: Release
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
  - ps: .\build.ps1
test: off
artifacts:  
  - path: '.\artifacts\*.nupkg'
    name: NuGet
deploy:  
  provider: NuGet
  name: production
  artifact: /.*\.nupkg/
  skip_symbols: false
  api_key:
    secure: yp9gBDjGkW+PXZu7oftjlUIRuz9JSuszKw70+jbGu1cWM8TNishkbwHZGu4JN+gK
  on:
    branch: master